import { get, put, del, post } from './api.client';

import type { Business, ApiResponse, PaginatedResponse } from './types';

export type BusinessFilters = {
  page?: number;
  per_page?: number;
  search?: string;
  status?: string;
  status_in?: string;
  verification_status?: string;
  country?: string;
  city?: string;
  timezone?: string;
  created_from?: string;
  created_to?: string;
  sort_by?: string;
  sort_dir?: 'asc' | 'desc';
};

/** Credentials generated by the server when an application is created. */
export type AppCredentials = { app_id: string; app_secret: string };

export const businessService = {
  // Get all businesses
  getAll: async (params?: BusinessFilters) => {
    const response = await get<ApiResponse<PaginatedResponse<Business>>>('/businesses', { params });
    return response.data;
  },

  // Get single business
  getById: async (id: number) => {
    const response = await get<ApiResponse<Business>>(`/businesses/${id}`);
    return response.data;
  },

  /**
   * Create an application. The API generates the app key/secret and returns
   * them alongside the record so they can be shown once to the user.
   */
  create: async (data: Partial<Business>) => {
    const response = await post<ApiResponse<{ business: Business; credentials: AppCredentials }>>(
      '/businesses',
      data
    );
    return response.data;
  },

  // Update business
  update: async (id: number, data: Partial<Business>) => {
    const response = await put<ApiResponse<Business>>(`/businesses/${id}`, data);
    return response.data;
  },

  // Delete business
  delete: async (id: number) => {
    const response = await del<ApiResponse<void>>(`/businesses/${id}`);
    return response.data;
  },

  // Get business stats
  getStats: async (id: number) => {
    const response = await get<ApiResponse<any>>(`/businesses/${id}/stats`);
    return response.data;
  },

  // Regenerate app credentials
  regenerateCredentials: async (id: number) => {
    const response = await post<ApiResponse<AppCredentials>>(
      `/businesses/${id}/regenerate-credentials`,
      {}
    );
    return response.data;
  },
};

